
export const nft_order = {
    'Total Fat/Lipides': 1,
    'Saturated/saturés': 2,
    'Trans / trans': 3,
    'Polyunsaturated/polyinsaturés': 4,
    'Omega-6/ oméga-6': 5,
    'Omega-3/ oméga-3': 6,
    'Monounsaturated/monoinsaturés': 7,
    'Total Carbohydrate / Glucides': 8,
    'Dietary Fibre / Fibres alimentaires': 9,
    'Soluble Fibre/Fibres solubles': 10,
    'Insoluble Fibre / Fibres insolubles': 11,
    'Sugars / Sucres': 12,
    'Sugar Alcohols /Polyalcools': 13,
    'Starch/Amidon': 14,
    'Protein / Protéines': 15,
    'Cholesterol/Cholestérol': 16,
    'Sodium': 17,
    'Potassium': 18,
    'Calcium': 19,
    'Iron / Fer': 20,
    'Vitamin A/Vitamine A': 21,
    'Vitamin C/Vitamine C': 22,
    'Vitamin D/Vitamine D': 23,
    'Vitamin E /Vitamine E': 24,
    'Vitamin K/Vitamine K': 25,
    'Thiamine': 26,
    'Riboflavin/Riboflavine': 27,
    'Niacin / Niacine': 28,
    'Vitamin B/Vitamine B,': 29,
    'Folate': 30,
    'Vitamin B,2/Vitamine B1,': 31,
    'Biotin / Biotine': 32,
    'Pantothenate / Pantothénate': 33,
    'Choline': 34,
    'Phosphorous/Phosphore': 35,
    'Iodide / Iode': 36,
    'Magnesium/Magnésium': 37,
    'Zinc': 38,
    'Selenium/Sélénium': 39,
    'Copper/Cuivre': 40,
    'Manganese / Manganèse': 41,
    'Chromium/Chrome': 42,
    'Molybdenum / Molybdène': 43,
    'Chloride/Chlorure': 44
}

export const nutrientMatches = {
    'Total Fat/Lipides': ['FAT (TOTAL LIPIDS)'],
    'Saturated/saturés': ['FATTY ACIDS, SATURATED, 10:0, DECANOIC',
        'FATTY ACIDS, SATURATED, 12:0, DODECANOIC',
        'FATTY ACIDS, SATURATED, 13:0 TRIDECANOIC',
        'FATTY ACIDS, SATURATED, 14:0, TETRADECANOIC',
        'FATTY ACIDS, SATURATED, 15:0, PENTADECANOIC',
        'FATTY ACIDS, SATURATED, 16:0, HEXADECANOIC',
        'FATTY ACIDS, SATURATED, 17:0, HEPTADECANOIC',
        'FATTY ACIDS, SATURATED, 18:0, OCTADECANOIC',
        'FATTY ACIDS, SATURATED, 20:0, EICOSANOIC',
        'FATTY ACIDS, SATURATED, 22:0, DOCOSANOIC',
        'FATTY ACIDS, SATURATED, 24:0, TETRACOSANOIC',
        'FATTY ACIDS, SATURATED, 4:0, BUTANOIC',
        'FATTY ACIDS, SATURATED, 6:0, HEXANOIC',
        'FATTY ACIDS, SATURATED, 8:0, OCTANOIC',
        'FATTY ACIDS, SATURATED, TOTAL'],
    'Trans / trans': ['FATTY ACIDS, TOTAL TRANS-MONOENOIC',
        'FATTY ACIDS, TOTAL TRANS-POLYENOIC',
        'FATTY ACIDS, TRANS, TOTAL'],
    'Polyunsaturated/polyinsaturés': ['FATTY ACIDS, POLYUNSATURATED, 18:2 9c,13c',
        'FATTY ACIDS, POLYUNSATURATED, 18:2 9c,14c',
        'FATTY ACIDS, POLYUNSATURATED, 18:2 9c,15c',
        'FATTY ACIDS, POLYUNSATURATED, 18:2 c,c n-6,  LINOLEIC, OCTADECADIENOIC',
        'FATTY ACIDS, POLYUNSATURATED, 18:2i, LINOLEIC, OCTADECADIENOIC',
        'FATTY ACIDS, POLYUNSATURATED, 18:2t NOT FURTHER DEFINED, LINOLEIC, OCTADECADIENOIC',
        'FATTY ACIDS, POLYUNSATURATED, 18:2t,t , OCTADECADIENENOIC',
        'FATTY ACIDS, POLYUNSATURATED, 18:2undifferentiated, LINOLEIC, OCTADECADIENOIC',
        'FATTY ACIDS, POLYUNSATURATED, 18:3 c,c,c n-3  LINOLENIC, OCTADECATRIENOIC',
        'FATTY ACIDS, POLYUNSATURATED, 18:3 c,c,c n-6, g-LINOLENIC, OCTADECATRIENOIC',
        'FATTY ACIDS, POLYUNSATURATED, 18:3i, LINOLENIC, OCTADECATRIENOIC',
        'FATTY ACIDS, POLYUNSATURATED, 18:3undifferentiated, LINOLENIC, OCTADECATRIENOIC',
        'FATTY ACIDS, POLYUNSATURATED, 18:4, OCTADECATETRAENOIC',
        'FATTY ACIDS, POLYUNSATURATED, 20:2 c,c  EICOSADIENOIC',
        'FATTY ACIDS, POLYUNSATURATED, 20:3 n-3 EICOSATRIENOIC',
        'FATTY ACIDS, POLYUNSATURATED, 20:3 n-6, EICOSATRIENOIC',
        'FATTY ACIDS, POLYUNSATURATED, 20:3, EICOSATRIENOIC',
        'FATTY ACIDS, POLYUNSATURATED, 20:4 n-6, ARACHIDONIC',
        'FATTY ACIDS, POLYUNSATURATED, 20:4, EICOSATETRAENOIC',
        'FATTY ACIDS, POLYUNSATURATED, 20:5 n-3, EICOSAPENTAENOIC (EPA)',
        'FATTY ACIDS, POLYUNSATURATED, 21:5',
        'FATTY ACIDS, POLYUNSATURATED, 22:2, DOCOSADIENOIC',
        'FATTY ACIDS, POLYUNSATURATED, 22:3,',
        'FATTY ACIDS, POLYUNSATURATED, 22:4 n-6, DOCOSATETRAENOIC',
        'FATTY ACIDS, POLYUNSATURATED, 22:5 n-3, DOCOSAPENTAENOIC (DPA)',
        'FATTY ACIDS, POLYUNSATURATED, 22:5n-6',
        'FATTY ACIDS, POLYUNSATURATED, 22:6 n-3, DOCOSAHEXAENOIC (DHA)',
        'FATTY ACIDS, POLYUNSATURATED, CONJUGATED, 18:2 cla, LINOLEIC, OCTADECADIENOIC',
        'FATTY ACIDS, POLYUNSATURATED, TOTAL'],
    'Omega-6/ oméga-6': ['FATTY ACIDS, POLYUNSATURATED, TOTAL OMEGA   N-6'],
    'Omega-3/ oméga-3': ['FATTY ACIDS, POLYUNSATURATED, TOTAL OMEGA  N-3'],
    'Monounsaturated/monoinsaturés': ['FATTY ACIDS, MONOUNSATURATED,  24:1undifferentiated, TETRACOSENOIC',
        'FATTY ACIDS, MONOUNSATURATED, 12:1, LAUROLEIC',
        'FATTY ACIDS, MONOUNSATURATED, 14:1, TETRADECENOIC',
        'FATTY ACIDS, MONOUNSATURATED, 15:1, PENTADECENOIC',
        'FATTY ACIDS, MONOUNSATURATED, 16:1c, HEXADECENOIC',
        'FATTY ACIDS, MONOUNSATURATED, 16:1t, HEXADECENOIC',
        'FATTY ACIDS, MONOUNSATURATED, 16:1undifferentiated, HEXADECENOIC',
        'FATTY ACIDS, MONOUNSATURATED, 17:1, HEPTADECENOIC',
        'FATTY ACIDS, MONOUNSATURATED, 18:1 10c',
        'FATTY ACIDS, MONOUNSATURATED, 18:1 10t',
        'FATTY ACIDS, MONOUNSATURATED, 18:1 11c',
        'FATTY ACIDS, MONOUNSATURATED, 18:1 11t',
        'FATTY ACIDS, MONOUNSATURATED, 18:1 12c',
        'FATTY ACIDS, MONOUNSATURATED, 18:1 12t',
        'FATTY ACIDS, MONOUNSATURATED, 18:1 13c',
        'FATTY ACIDS, MONOUNSATURATED, 18:1 14c',
        'FATTY ACIDS, MONOUNSATURATED, 18:1 15c',
        'FATTY ACIDS, MONOUNSATURATED, 18:1 16c',
        'FATTY ACIDS, MONOUNSATURATED, 18:1 16t',
        'FATTY ACIDS, MONOUNSATURATED, 18:1 4t',
        'FATTY ACIDS, MONOUNSATURATED, 18:1 5t',
        'FATTY ACIDS, MONOUNSATURATED, 18:1 6t-8t',
        'FATTY ACIDS, MONOUNSATURATED, 18:1c, OCTADECENOIC',
        'FATTY ACIDS, MONOUNSATURATED, 18:1t, OCTADECENOIC',
        'FATTY ACIDS, MONOUNSATURATED, 18:1undifferentiated, OCTADECENOIC',
        'FATTY ACIDS, MONOUNSATURATED, 20:1 5c',
        'FATTY ACIDS, MONOUNSATURATED, 20:1, EICOSENOIC',
        'FATTY ACIDS, MONOUNSATURATED, 22:1c, DOCOSENOIC',
        'FATTY ACIDS, MONOUNSATURATED, 22:1t, DOCOSENOIC',
        'FATTY ACIDS, MONOUNSATURATED, 22:1undifferentiated, DOCOSENOIC',
        'FATTY ACIDS, MONOUNSATURATED, 24:1c, TETRACOSENOIC',
        'FATTY ACIDS, MONOUNSATURATED, TOTAL'],
    'Saturated + trans / Saturés + trans': ['FATTY ACIDS, SATURATED + TRANS, TOTAL'],
    'Total Carbohydrate / Glucides': ['CARBOHYDRATE, TOTAL (BY DIFFERENCE)', 'OTHERCARBOHYDRATES'],
    'Dietary Fibre / Fibres alimentaires': ['FIBRE, TOTAL DIETARY'],
    'Soluble Fibre/Fibres solubles': ['FIBRE, SOLUBLE DIETARY FIBRE'],
    'Insoluble Fibre / Fibres insolubles': ['FIBRE, INSOLUBLE DIETARY FIBRE'],
    'Sugars / Sucres': ['SUGARS, TOTAL', 'Sugars, total including NLEA'],
    'Sugar Alcohols /Polyalcools': ['SUGAR_ALCOHOLS'],
    'Starch/Amidon': ['STARCH'],
    'Protein / Protéines': ['PROTEIN'],
    'Cholesterol/Cholestérol': ['CHOLESTEROL'],
    'Sodium': ['SODIUM'],
    'Potassium': ['POTASSIUM'],
    'Calcium': ['CALCIUM'],
    'Iron / Fer': ['IRON'],
    'Vitamin A/Vitamine A': ['VITAMIN A (INTERNATIONAL UNITS)'],
    'Vitamin C/Vitamine C': ['VITAMIN C'],
    'Vitamin D/Vitamine D': ['VITAMIN D (D2 + D3)', 'VITAMIN D (INTERNATIONAL UNITS)', 'VITAMIN D2, ERGOCALCIFEROL', 'VITAMIN D3, CHOLECALCIFEROL'],
    'Vitamin E /Vitamine E': ['VITAMIN E, TOTAL TOCOPHEROLS'],
    'Vitamin K/Vitamine K': ['VITAMIN K', 'VITAMIN K (DIHYDROPHYLLOQUINONE)', 'VITAMIN K (MENAQUINONE-4)', 'VITAMIN K (PHYLLOQUINONE)'],
    'Thiamine': ['THIAMINE'],
    'Riboflavin/Riboflavine': ['RIBOFLAVIN'],
    'Niacin / Niacine': ['NIACIN (NICOTINIC ACID) PREFORMED', 'TOTAL NIACIN EQUIVALENT'],
    'Vitamin B6/Vitamine B6,': ['VITAMIN B-6'],
    'Folate': ['DIETARY FOLATE EQUIVALENTS', 'NATURALLY OCCURRING FOLATE'],
    'Vitamin B12/Vitamine B12,': ['VITAMIN B-12', 'VITAMIN B12, ADDED'],
    'Biotin / Biotine': ['BIOTIN'],
    'Pantothenate / Pantothénate': [],
    'Choline': ['CHOLINE, TOTAL'],
    'Phosphorous/Phosphore': ['PHOSPHORUS'],
    'Iodide / Iode': ['IODIDE'],
    'Magnesium/Magnésium': ['MAGNESIUM'],
    'Zinc': ['ZINC'],
    'Selenium/Sélénium': ['SELENIUM'],
    'Copper/Cuivre': ['COPPER'],
    'Manganese / Manganèse': ['MANGANESE'],
    'Chromium/Chrome': ['CHROMIUM'],
    'Molybdenum / Molybdène': ['MOLYBDENUM'],
    'Chloride/Chlorure': ['CHLORIDE']
}

