  // constants/export/fieldMapping.js
  export const SODIUM_FIELD_MAPPING = {
    id: "FLAIME StoreProduct ID",
    nielsen_barcode: "UPC",
    store_product_code: "ItemId",
    product_profile_description: "PrdGpId",
    products_variety_pack_flag: "Multipart",
    most_recent_flag: "InSampleFinal",
    site_description: "LOthMar",
    'scrape_batch.datetime': "Delivery_Date",
    store_product_code: "LItemId",
    raw_upc: "LUPC",
    nielsen_upc: "LSalesUPC",
    'category.name': "LNielCat",
    site_name: "LDesc",
    raw_brand: "LBrand",
    manufacturer: "LManuf",
    'scrape_batch.region': "LCtry",
    total_size_value: "LNQty",
    total_size_unit: "LNQtyUoM",
    'store.name': "LStorType",
    'scrape_batch.datetime': "LCollDate",
    dietary_info_description: "LHClm",
    dietary_info_description: "LOthPckStat",
    'ingredients.en': "LIngr",
    products_variety_pack_flag: "LMultiPart",
    nutrition_available_flag: "LNFT",
    raw_serving_size: "LCHM",
    serving_size: "LPSAmt",
    serving_size_unit: "LPSUoM"
  };
